# -*- coding: utf-8 -*-
"""Hot Jupiters (Kepler).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CLGhBY4rRaAVLT2Geec85WSrH9lZDtV
"""

!pip install juliet
!pip install astropy
!pip install lightkurve

import juliet
import matplotlib.pyplot as plt
import numpy as np
import zipfile
from astropy.io import fits
import lightkurve as lk
import os

# @title
with zipfile.ZipFile("/content/MAST_2025-11-02T1516.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/")

# @title
path = '/content/'
filename = 'kplr003861595-2009350155506_llc'
filepath = path + filename + '.fits'
hdul = fits.open(filepath)
header = hdul[0].header
print(header["QUARTER"])

t, f, ferr = juliet.get_TESS_data(filepath)

kepler_integer = 2454833.0
period = 3.8493733               # days
t0_BJD = 2455005.92415
t0_BKJD = t0_BJD - kepler_integer
t0 = t0_BKJD
duration = (2.6 + 0.1)/24       # days

lc = lk.LightCurve(time=t, flux=f, flux_err=ferr).remove_nans()
mask = lc.create_transit_mask(period=period, transit_time=t0, duration=duration)
#mask_secondary = lc.create_transit_mask(period=period, transit_time=t0 + period/2, duration=duration)

# Plot data:
plt.figure(figsize=(12,4), dpi=80)

# out-of-transit in blue
plt.errorbar(lc.time.value[~mask], lc.flux.value[~mask],
             yerr=lc.flux_err.value[~mask],
             fmt='.', color='tab:blue', alpha=0.4, label='Out of transit')

# plt.errorbar(lc.time.value[~mask_secondary], lc.flux.value[~mask_secondary],
#              yerr=lc.flux_err.value[~mask_secondary],
#              fmt='.', color='tab:blue', alpha=0.4, label='Out of transit')

# in-transit in orange
plt.errorbar(lc.time.value[mask], lc.flux.value[mask],
             yerr=lc.flux_err.value[mask],
             fmt='.', color='tab:orange', alpha=0.9, label='Masked (transit)')
# plt.errorbar(lc.time.value[mask_secondary], lc.flux.value[mask_secondary],
#              yerr=lc.flux_err.value[mask_secondary],
#              fmt='.', color='tab:red', alpha=0.9, label='Masked (transit)')

plt.xlabel("Time (BTJD)")
plt.ylabel("Flux")
plt.legend()
plt.show()

# @title
# mask = mask_primary | mask_secondary
flattened_lc = lc.flatten(window_length=41,polyorder=2, mask=mask)
plt.figure(figsize=(12, 4), dpi=80)

plt.errorbar(flattened_lc.time.value[~mask], flattened_lc.flux.value[~mask], yerr=flattened_lc.flux_err.value[~mask], fmt='.', color='blue', alpha=0.5)
plt.errorbar(flattened_lc.time.value[mask], flattened_lc.flux.value[mask], yerr=flattened_lc.flux_err.value[mask], fmt='.', label='Transit',color='orange',alpha=0.9)
plt.xlabel('Time (BJD)')
plt.ylabel('Flux')
plt.legend()
plt.show()

binned_lc = flattened_lc.bin(time_bin_size=5/1440)
plt.errorbar(binned_lc.time.value, binned_lc.flux.value, \
             yerr = binned_lc.flux_err.value, fmt = '.' , alpha = 0.1)

# @title
# Load dataset into juliet, save results to a temporary folder called toi141_fit:
binned_lc = binned_lc.remove_nans()
print(binned_lc)
binned_lc.write(path + filename + '.txt', format="ascii.fixed_width", overwrite=True)

time, flux, flux_err, tbin_start, tbin_size = np.loadtxt(
    'kplr003861595-2009350155506_llc.txt',
    delimiter="|",
    skiprows=1,
    unpack=True,
    usecols=(1, 2, 3, 4, 5)
)

min_time = np.min(time)
max_time = np.max(time)
kepler_integer = 2454833.0
period = 3.8493733               # days
t0_BJD = 2455005.92415
# t0_BKJD = t0_BJD - kepler_integer
t0_BTJD = t0_BJD - 2457000
duration = (2.6 + 0.1)/24
t_mid_Kep = np.median(time)
N = np.round((t_mid_Kep - t0_BTJD)/period).astype(int)
t0 = t0_BTJD + N*period
print(t0)

lc = lk.LightCurve(time=time, flux=flux, flux_err=flux_err).remove_nans()

# Save data into those dictionaries:
times, fluxes, fluxes_error = {}, {}, {}

times['Kepler'], fluxes['Kepler'], fluxes_error['Kepler'] = lc.time.value,lc.flux.value,lc.flux_err.value

starting_point = {
    'P_p1':     3.8494,        # period [days]
    't0_p1':    t0,    # mid-transit time [BKJD]
    'p_p1':     0.0359,            # Rp/R*
    'b_p1':     0.9501,    # impact parameter
    'rho':          106.8,   # kg/m^3
    'q1_Kepler':    0.3,
    'q2_Kepler':    0.3,
    'mflux_Kepler':     0.0,
    'sigma_w_Kepler': 10
}

with open('/content/priors - kepler.dat', 'r+') as f:
  lines = f.readlines()

lines[1] = 't0_p1'+' '+'uniform'+' '+str(min_time)+','+str(max_time)+'\n'

with open('/content/priors - kepler.dat', 'w') as f:
  f.writelines(lines)

dataset = juliet.load(priors='/content/priors - kepler.dat',  t_lc=times,       # dictionary with one instrument
    y_lc=fluxes,
    yerr_lc=fluxes_error, out_folder = '/content/')
dataset.starting_point = starting_point
# print("NaNs in flux?", np.any(np.isnan(binned_lc.flux)))
# print("NaNs in flux_err?", np.any(np.isnan(binned_lc.flux_err)))
# print("Zero or negative flux_err?", np.any(binned_lc.flux_err <= 0))
# Fit and absorb results into a juliet.fit object:
results = dataset.fit(sampler = 'emcee', nwalkers = 30, nsteps = 10000, nburnin = 1000) #nwalkers should be twice the number of parameters



# Extract median model and the ones that cover the 68% credibility band around it:
transit_model, transit_up68, transit_low68  = results.lc.evaluate('Kepler', return_err=True)
# To plot the phased lighcurve we need the median period and time-of-transit center:
P, t0 = np.median(results.posteriors['posterior_samples']['P_p1']),\
        np.median(results.posteriors['posterior_samples']['t0_p1'])

# Get phases:
phases = juliet.get_phases(lc.time.value, P, t0)

import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import numpy as np
import lightkurve as lk

mpl.rcParams.update({
    "figure.dpi": 300,
    "font.family": "serif",
    "mathtext.fontset": "dejavuserif",
    "axes.labelsize": 20,
    "xtick.labelsize": 13,
    "ytick.labelsize": 13,
    "axes.linewidth": 1.1,
    "xtick.major.width": 1.0,
    "ytick.major.width": 1.0,
    "xtick.minor.width": 0.8,
    "ytick.minor.width": 0.8,
    "xtick.major.size": 6,
    "ytick.major.size": 6,
    "xtick.minor.size": 3.5,
    "ytick.minor.size": 3.5,
    "axes.grid": False,
})

# -----------------------------
# Display binning only
# -----------------------------
bin_size = 30.0 / 1440.0   # 30 min bins for cleaner presentation
resid_bin_size = 40.0/1440
binned_lc = lc.bin(time_bin_size=bin_size)

residuals = lc.flux.value - transit_model
resid_lc = lk.LightCurve(
    time=lc.time.value,
    flux=residuals,
    flux_err=lc.flux_err.value
)
binned_resid_lc = resid_lc.bin(time_bin_size=resid_bin_size)

# Fold phases in hours
phase_unbinned = juliet.get_phases(lc.time.value, P, t0) * P * 24.0
phase_binned   = juliet.get_phases(binned_lc.time.value, P, t0) * P * 24.0
phase_resid    = juliet.get_phases(binned_resid_lc.time.value, P, t0) * P * 24.0

# Sort model
srt = np.argsort(phase_unbinned)
x_model = phase_unbinned[srt]

# Transit depth in ppm
depth_unbinned = (1.0 - lc.flux.value) * 1e6
depth_binned   = (1.0 - binned_lc.flux.value) * 1e6
depth_binned_err = binned_lc.flux_err.value * 1e6

model_ppm = (1.0 - transit_model[srt]) * 1e6
band_low  = (1.0 - transit_up68[srt]) * 1e6
band_high = (1.0 - transit_low68[srt]) * 1e6

# Residuals in ppm
resid_ppm = binned_resid_lc.flux.value * 1e6
resid_err_ppm = binned_resid_lc.flux_err.value * 1e6

# Sort residuals
ir = np.argsort(phase_resid)
phase_resid = phase_resid[ir]
resid_ppm = resid_ppm[ir]
resid_err_ppm = resid_err_ppm[ir]

# Figure
fig = plt.figure(figsize=(10.0, 7.0))
gs = gridspec.GridSpec(2, 1, height_ratios=[3.0, 1.0], hspace=0.06)

ax1 = fig.add_subplot(gs[0])
ax2 = fig.add_subplot(gs[1], sharex=ax1)

# White background
ax1.set_facecolor("white")
ax2.set_facecolor("white")
fig.patch.set_facecolor("white")

# ---- Top panel ----
# Unbinned cloud: faint grey
ax1.scatter(
    phase_unbinned,
    depth_unbinned,
    s=8,
    color="0.80",
    alpha=0.35,
    linewidths=0,
    rasterized=True,
    zorder=1
)

# Credible band: very subtle
ax1.fill_between(
    x_model,
    band_low,
    band_high,
    color="0.82",
    alpha=0.25,
    zorder=2
)

# Binned points: dark navy
ax1.errorbar(
    phase_binned,
    depth_binned,
    yerr=depth_binned_err,
    fmt='o',
    ms=2.8,
    mfc='#8a3f14',
    mec='#8a3f14',
    mew=0.0,
    ecolor='#8a3f14',
    elinewidth=0.45,
    capsize=0,
    alpha=0.85,
    zorder=4,
)

# Model
ax1.plot(
    x_model,
    model_ppm,
    color='red',
    lw=1.4,
    zorder=5
)

ax1.axhline(0, color='0.6', lw=1.0, ls='--', zorder=0)

ax1.set_ylabel('Transit depth (ppm)', fontsize=18)
ax1.set_xlim([-3.0, 3.0])

# Invert y-axis
ymax = np.nanmax([np.nanmax(depth_unbinned), np.nanmax(band_high)])
ymin = np.nanmin([np.nanmin(depth_unbinned), np.nanmin(band_low)])
ax1.set_ylim(4000, -4000)

plt.setp(ax1.get_xticklabels(), visible=False)
ax1.minorticks_on()

# ---- Residuals panel ----
# Binned residuals only
ax2.errorbar(
    phase_resid,
    resid_ppm,
    yerr=resid_err_ppm,
    fmt='o',
    ms=3.4,
    mfc='#8a3f14',
    mec='#8a3f14',
    mew=0.0,
    ecolor='#8a3f14',
    elinewidth=0.5,
    capsize=0,
    alpha=0.95,
    zorder=3
)

# ax2.scatter(phase_resid, resid_ppm, s=10, color='#1f2f4a', alpha=0.9)

ax2.axhline(0, color='0.55', lw=0.9, ls='--')

ax2.set_xlabel('Time from mid-transit (hours)', fontsize=18)
ax2.set_ylabel('Residuals\n(ppm)', fontsize=18)
ax2.minorticks_on()

# Tight but not cramped residual limits
rmax = np.nanmax(np.abs(resid_ppm)+resid_err_ppm)
ax2.set_ylim([2000, -2000])

for ax in (ax1, ax2):
    for spine in ax.spines.values():
        spine.set_linewidth(1.0)

plt.tight_layout()
plt.show()

import matplotlib.gridspec as gridspec

# Plot the data. First, time versus flux --- plot only the median model here:
fig = plt.figure(figsize=(12,4), dpi=300)
gs = gridspec.GridSpec(1, 2, width_ratios=[2,1])
ax1 = plt.subplot(gs[0])

plt.errorbar(dataset.times_lc['Kepler'], dataset.data_lc['Kepler'], yerr=dataset.errors_lc['Kepler'], fmt='.', color='black', alpha=0.3)

# Plot the median model:
ax1.plot(dataset.times_lc['Kepler'], transit_model, color='red',zorder=10)

# Plot portion of the lightcurve, axes, etc.:
#ax1.set_xlim([np.min(dataset.times_lc['TESS']),np.max(dataset.times_lc['TESS'])])
ax1.set_ylim([0.9975,1.0025])
#ax1.set_xlim([2802,2803])
ax1.set_xlabel('Time (BJD - 2454833)')
ax1.set_ylabel('Relative flux')

# Now plot phased model; plot the error band of the best-fit model here:
ax2 = plt.subplot(gs[1])
ax2.errorbar(phases, lc.flux.value, \
             yerr = lc.flux_err.value, fmt = '.', alpha = 0.3, color='black')
idx = np.argsort(phases)
ax2.plot(phases[idx],transit_model[idx], color='red',zorder=10)
ax2.fill_between(phases[idx],transit_up68[idx],transit_low68[idx],\
                 color='white',alpha=0.5,zorder=5)
ax2.set_xlabel('Phases')
ax2.set_xlim([-0.05,0.05])
ax1.set_ylim([0.9975,1.0025])

files_to_rename = {
    "posteriors.dat": "posteriors_kplr003861595-2012004120508_llc.dat",
    "emcee_posteriors.pkl": "emcee_kplr003861595-2012004120508_llc.pkl"
}

for old, new in files_to_rename.items():
    if os.path.exists(old):
        os.rename(old, new)

import matplotlib.gridspec as gridspec
import numpy as np
import matplotlib.pyplot as plt
import lightkurve as lk
from scipy.ndimage import gaussian_filter1d

# -----------------------------------
# Bin light curve and residuals
# -----------------------------------
binned_lc = lc.bin(time_bin_size=60.0/1440)

unbinned_residuals = lc.flux.value - transit_model
residuals_lc = lk.LightCurve(
    time=lc.time.value,
    flux=unbinned_residuals,
    flux_err=lc.flux_err.value
)
binned_residuals_lc = residuals_lc.bin(time_bin_size=60.0/1440)

# Folded phases
phases_unbinned = juliet.get_phases(lc.time.value, P, t0) * P * 24.0
phases_binned = juliet.get_phases(binned_lc.time.value, P, t0) * P * 24.0
phases_resid = juliet.get_phases(binned_residuals_lc.time.value, P, t0) * P * 24.0

# Sort model arrays for plotting
idx = np.argsort(phases_unbinned)

# -----------------------------------
# Figure layout: top full width, bottom full width
# -----------------------------------
fig = plt.figure(figsize=(8, 5.5), dpi=300)
gs = gridspec.GridSpec(2, 1, height_ratios=[2.2, 1.2], hspace=0.03)

ax1 = plt.subplot(gs[0])
ax2 = plt.subplot(gs[1], sharex=ax1)

# -----------------------------------
# TOP PANEL: folded light curve
# -----------------------------------
# unbinned points
ax1.errorbar(
    phases_unbinned,
    lc.flux.value,
    yerr=lc.flux_err.value,
    fmt='.',
    color='blue',
    alpha=0.08,
    markersize=2,
    label='Kepler data'
)

# phase-averaged / binned points
ax1.errorbar(
    phases_binned,
    binned_lc.flux.value,
    yerr=binned_lc.flux_err.value,
    fmt='o',
    mfc='white',
    mec='blue',
    mew=0.8,
    ms=4.5,
    ecolor='blue',
    elinewidth=0.5,
    capsize=0,
    alpha=0.95,
    label='phase-averaged'
)

# median model
ax1.plot(
    phases_unbinned[idx],
    transit_model[idx],
    color='black',
    zorder=10,
    lw=1.2
)

# posterior band
ax1.fill_between(
    phases_unbinned[idx],
    transit_low68[idx],
    transit_up68[idx],
    color='lightgray',
    alpha=0.6,
    zorder=5
)

ax1.set_ylabel('Relative flux')
ax1.set_xlim([-2.4, 2.4])   # hours
ax1.set_ylim([0.9850, 1.0025])
ax1.legend(loc='lower right', frameon=True)
ax1.grid(alpha=0.25)

# Hide top x tick labels
plt.setp(ax1.get_xticklabels(), visible=False)

# -----------------------------------
# BOTTOM PANEL: residuals
# -----------------------------------
resid_ppm = binned_residuals_lc.flux.value * 1e6
resid_err_ppm = binned_residuals_lc.flux_err.value * 1e6

ax2.scatter(
    phases_resid,
    resid_ppm,
    facecolors='white',
    edgecolors='blue',
    s=25,
    linewidths=0.8,
    alpha=0.9,
    label='residuals',
    zorder = 5
)

# zero line
ax2.axhline(0, color='black', lw=1.0, alpha=0.7)

# optional smoothed residual curve
def running_mean(y, window=7):
    kernel = np.ones(window) / window
    return np.convolve(y, kernel, mode='same')

idx_resid = np.argsort(phases_resid)
ph_sorted = phases_resid[idx_resid]
resid_sorted = resid_ppm[idx_resid]

smooth_resid = gaussian_filter1d(resid_ppm, sigma=3)
ax2.plot(phases_resid, smooth_resid, color='red', lw=2.5, zorder=20, label='model residuals')

ax2.set_xlabel('Folded time (hours)')
ax2.set_ylabel('Residual flux (ppm)')
ax2.set_xlim([-2.4, 2.4])
ax2.set_ylim([-130, 130])
ax2.legend(loc='lower right', frameon=True)
ax2.grid(alpha=0.25)

plt.tight_layout()
plt.show()

print(np.nanmin(smooth_resid), np.nanmax(smooth_resid))
print("Residual RMS (ppm):", np.nanstd(binned_residuals_lc.flux.value) * 1e6)